# This is useful for for debugging Dockerfile locally
services:
  app:
    build:
      context: .
      dockerfile: 'component/Dockerfile'
      args:
        FOLDER: '/app/component'
        IDENTIFIER: 'component'
    container_name: spin-component-test-prod
    working_dir: /app
    ports:
      - '80:80'
    environment:
      - FOLDER=/app/component
