# Use official PHP image with Apache
FROM php:8.3-apache

# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app/component-name

# Install required packages
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    curl \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    mariadb-client
RUN docker-php-ext-install pdo pdo_mysql

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory
WORKDIR ${FOLDER}

# Add user 1000
RUN groupadd -g 1000 www && \
    useradd -u 1000 -g 1000 -m -s /bin/bash www

USER 0

# Expose Apache port
EXPOSE 80

# Set entrypoint command
ENTRYPOINT $FOLDER/entrypoint.sh
